version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: alpha_arena_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: alpha_arena
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: alpha_arena_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: alpha_arena_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 3001 --reload
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: alpha_arena_celery_worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: alpha_arena_celery_beat
    command: celery -A app.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

